-- 1% 저널 연도별 국가 통계 수집 쿼리
DROP TABLE TMP_NJTD_1_COCT_ST CASCADE CONSTRAINTS PURGE;
CREATE TABLE TMP_NJTD_1_COCT_ST AS
SELECT DISTINCT A.EID, A.PUBLICATION_YEAR, A.COUNTRY_CODE
FROM (
  SELECT EID, PUBLICATION_YEAR, COUNTRY_CODE
  FROM NEON_2018_DOCUMENT_CN 
  WHERE EID IN (
      SELECT DISTINCT EID
      FROM NEON_2018_JOURNAL_TOP_DOCUMENT
      WHERE SOURCE_ID IN (
          SELECT JOURNAL_ID
          FROM NEON_2018_JOURNAL_TOPRATE
          WHERE TOPRATE <= 0.01
      )
  )
) A
WHERE A.EID IN (
    SELECT DISTINCT EID 
    FROM ( 
      SELECT EID, COUNT(COUNTRY_CODE) AS CNT
      FROM (
        SELECT DISTINCT EID, COUNTRY_CODE
        FROM NEON_2018_DOCUMENT_CN
      )
      GROUP BY EID
    ) 
    WHERE CNT >= 2
) AND PUBLICATION_YEAR BETWEEN '2007' AND '2017';

CREATE INDEX IDX_TN1CCST_EID ON TMP_NJTD_1_COCT_ST(EID);
CREATE INDEX IDX_TN1CCST_PY ON TMP_NJTD_1_COCT_ST(PUBLICATION_YEAR);
CREATE INDEX IDX_TN1CCST_CN ON TMP_NJTD_1_COCT_ST(COUNTRY_CODE);


 
-- 10% 저널 연도별 국가 통계 수집 쿼리- 공동연구 국가 건수
DROP TABLE TMP_NJTD_10_COCT_ST CASCADE CONSTRAINTS PURGE;
CREATE TABLE TMP_NJTD_10_COCT_ST AS
SELECT DISTINCT A.EID, A.PUBLICATION_YEAR, A.COUNTRY_CODE
FROM (
  SELECT EID, PUBLICATION_YEAR, COUNTRY_CODE
  FROM NEON_2018_DOCUMENT_CN 
  WHERE EID IN (
      SELECT DISTINCT EID
      FROM NEON_2018_JOURNAL_TOP_DOCUMENT
      WHERE SOURCE_ID IN (
          SELECT JOURNAL_ID
          FROM NEON_2018_JOURNAL_TOPRATE
          WHERE TOPRATE <= 0.1
      )
  )
) A
WHERE A.EID IN (
  SELECT DISTINCT EID 
  FROM ( 
    SELECT EID, COUNT(COUNTRY_CODE) AS CNT
   FROM (
      SELECT DISTINCT EID, COUNTRY_CODE
      FROM NEON_2018_DOCUMENT_CN
    )
    GROUP BY EID
  )
  WHERE CNT >= 2
) AND PUBLICATION_YEAR BETWEEN '2007' AND '2017';
CREATE INDEX IDX_TN10CCST_EID ON TMP_NJTD_10_COCT_ST(EID);
CREATE INDEX IDX_TN10CCST_PY ON TMP_NJTD_10_COCT_ST(PUBLICATION_YEAR);
CREATE INDEX IDX_TN10CCST_CN ON TMP_NJTD_10_COCT_ST(COUNTRY_CODE);

-- 저널 1% 교신저자 + 1저자 국가 건수


-- 저널 10% 교신저자 + 1저자 국가 건수